Feature/check package versions
moneymeets/action-setup-python-poetry pull request #22
Opened 2024-04-10 14:36 UTC by pchorus

As discussed @zyv and I created a GitHub Action to check package versions configured in `pyproject.toml`.

We want to avoid pinned versions and also lax configuration like using `^` or `>=`.

All we want to allow is `*` as general solution which is always the preferred version config.
If we need to pin version, we should use `~` which allows updates to minor or patch versions (depending on the version number that follows the `~`), but never updates major versions which can contain breaking changes.

We have tested this action in `django-insurance-api-v2` by using the feature branch of this repository here.
I run it with current `pyproject.toml` (https://github.com/moneymeets/django-insurance-api-v2/actions/runs/8632210966/job/23664358558) containing some errors and also with a fixed `pyproject.toml` (https://github.com/moneymeets/django-insurance-api-v2/actions/runs/8632335916/job/23662773927).

Please share your thoughts.
Is this what we are aiming for?

2024-04-10 14:55 UTC, zyv approved these changes
Our code is gold! :)

2024-04-10 16:00 UTC, mm-matthias commented on action.yml
> +    - run: python ${{ github.action_path }}/suspicious-package-versions.py
```suggestion
    - run: python ${{ github.action_path }}/invalid-package-versions.py
```
Or something other than `invalid`. To me `suspicious` suggests that this is some sort of security check which it is not.

2024-04-10 16:04 UTC, mm-matthias approved these changes
I've suggest a naming change and some minor typing, but that's it. 

What you write in the PR description seems to make sense to me. I guess we need to see if this works with our repositories or whether we have any repositories that break the implemented rule.
If we ever need a different rule for whatever reason we can still discuss it as it comes up and possibly modify this versioning rule here.

2024-04-10 16:04 UTC, mm-matthias commented on suspicious-package-versions.py
> +def extract_version(version):
```suggestion
def get_version(version: Union[str, dict]) -> str:
```

2024-04-10 16:04 UTC, mm-matthias commented on suspicious-package-versions.py
> +suspicious_versions = []
```suggestion
invalid_versions = []
```
Or whatever else.

2024-04-10 16:04 UTC, mm-matthias commented on suspicious-package-versions.py
> +        pass
I find this `pass` to be a little out of the ordinary, but I can live with it.

2024-04-10 16:04 UTC, mm-matthias commented on suspicious-package-versions.py
File name, see below.

2024-04-11 05:32 UTC, marns93 requested changes

2024-04-11 05:32 UTC, marns93 commented on action.yml
> +    - run: python ${{ github.action_path }}/suspicious-package-versions.py
What about `misconfigured`?

2024-04-11 05:32 UTC, marns93 commented on suspicious-package-versions.py
> +        *poetry_data["dev-dependencies"].items()
This is quite dangerous, because it is possible to create more dependency groups (https://python-poetry.org/docs/managing-dependencies/#dependency-groups). In this case the group will be ignored and nobody will notice this. 

Either we should check for `tool.poetry.group` and add every matching entry, even if there is nothing at the moment.
Or we should forbid additional dependency groups.

2024-04-11 05:35 UTC, marns93 commented
@pchorus In our daily I understood that we will forbid `^`, now we will forbid `>=` as well which is fine for me. Before this PR will be merged, we should notify everybody, because this pattern is used in some repositories and the pipeline will fail.

2024-04-11 06:23 UTC, zyv commented on action.yml
> +    - run: python ${{ github.action_path }}/suspicious-package-versions.py
I like invalid.

2024-04-11 06:29 UTC, zyv commented
> @pchorus In our daily I understood that we will forbid `^`, now we will forbid `>=` as well which is fine for me. Before this PR will be merged, we should notify everybody, because this pattern is used in some repositories and the pipeline will fail.

Yes, we decided that there is also no need for `>=`, because we can pin to `~1.2.3` if we need to, and we want to unpin as soon as possible anyways, so restriction on only minor updates does not matter. We prepared example changes for insurance API.

2024-04-11 07:10 UTC, marns93 requested changes

2024-04-11 07:10 UTC, marns93 commented on suspicious-package-versions.py
> +        *poetry_data["dev-dependencies"].items()
I think small unittests would be great

2024-04-11 07:23 UTC, marns93 commented
> > @pchorus In our daily I understood that we will forbid `^`, now we will forbid `>=` as well which is fine for me. Before this PR will be merged, we should notify everybody, because this pattern is used in some repositories and the pipeline will fail.
> 
> Yes, we decided that there is also no need for `>=`, because we can pin to `~1.2.3` if we need to, and we want to unpin as soon as possible anyways, so restriction on only minor updates does not matter. We prepared example changes for insurance API.

What about `boto3`?

```
boto3 = ">=1.26.148"  # Needed for dependency resolution. See also https://github.com/python-poetry/poetry/issues/5896.
```

Changing this to `~1.26.148` is not the same as `>=`. The issue is still open and we can't unpin.
Result would be `>=1.26.148 <1.27.0`. But we could use versions greater than `1.27.0`.

So I wonder if we really should remove `>=`.

2024-04-11 07:48 UTC, zyv commented on suspicious-package-versions.py
> +        *poetry_data["dev-dependencies"].items()
Can do some last pair programming on Friday.

2024-04-11 07:51 UTC, zyv commented
> > > @pchorus In our daily I understood that we will forbid `^`, now we will forbid `>=` as well which is fine for me. Before this PR will be merged, we should notify everybody, because this pattern is used in some repositories and the pipeline will fail.
> > 
> > 
> > Yes, we decided that there is also no need for `>=`, because we can pin to `~1.2.3` if we need to, and we want to unpin as soon as possible anyways, so restriction on only minor updates does not matter. We prepared example changes for insurance API.
> 
> What about `boto3`?
> 
> ```
> boto3 = ">=1.26.148"  # Needed for dependency resolution. See also https://github.com/python-poetry/poetry/issues/5896.
> ```
> 
> Changing this to `~1.26.148` is not the same as `>=`. The issue is still open and we can't unpin. Result would be `>=1.26.148 <1.27.0`. But we could use versions greater than `1.27.0`.
> 
> So I wonder if we really should remove `>=`.

Argh, stupid Poetry slow resolution :( Maybe we can allow ">" as a hack to make sure that this was added manually?

2024-04-11 07:53 UTC, mm-matthias commented
One could also add boto3 as an explicit exception to the checker.

2024-04-12 05:08 UTC, pchorus commented on action.yml
> +    - run: python ${{ github.action_path }}/suspicious-package-versions.py
Changed it to invalid.

2024-04-12 06:51 UTC, pchorus commented on suspicious-package-versions.py
> +        *poetry_data["dev-dependencies"].items()
I agree. I turned it into a full blown Poetry project containing ruff and unit tests.
Please re-review if everything makes sense to you.

File watchers for ruff do not work on my machine. Maybe I am doing something wrong.

2024-04-12 07:05 UTC, pchorus commented on suspicious-package-versions.py
> +        *poetry_data["dev-dependencies"].items()
Also, paths to test files only work for CI now. Running it in PyCharm fails. I would prefer having relative paths somehow. @zyv @mm-matthias

2024-04-12 11:28 UTC, mm-matthias commented on invalid_package_versions/runner.py
> +def get_version(version: str | dict):
```suggestion
def get_version(version: str | dict) -> str:
```

2024-04-12 11:29 UTC, mm-matthias commented on invalid_package_versions/runner.py
> +def check_invalid_package_versions(pyproject_data):
```suggestion
def check_invalid_package_versions(pyproject_data) -> Sequence[str]:
```

2024-04-12 11:29 UTC, mm-matthias commented on invalid_package_versions/runner.py
> +    return tuple(invalid_versions)
This could be a comprehension, but not sure you like it :)

2024-04-12 11:30 UTC, mm-matthias approved these changes
Did not test, but LGTM in general. I still need to talk to you guys about the "*" stuff.

2024-04-12 12:41 UTC, catcombo requested changes
I like the idea. Thank you for implementing this! However, I agree with @marns93 regarding limiting the minimum version of the `boto3` library. Poetry resolves dependencies a couple of minutes if you use a `*` or `~`. We should either exclude `boto3` from check or allow `>=`.

2024-04-12 12:41 UTC, catcombo commented on invalid_package_versions/runner.py
> +            invalid_versions.append((package, version_str))
```suggestion
        if version_str not in ("*", None) and not version_str.startswith("~"):
            invalid_versions.append((package, version_str))
```

2024-04-15 06:03 UTC, pchorus commented on invalid_package_versions/runner.py
> +def get_version(version: str | dict):
Return type is actually `str | None`.

2024-04-15 06:07 UTC, pchorus commented on invalid_package_versions/runner.py
> +def check_invalid_package_versions(pyproject_data):
Type is actually `Sequence[Sequence[str, str]]`.

2024-04-15 06:14 UTC, catcombo commented on invalid_package_versions/runner.py
> +def check_invalid_package_versions(pyproject_data):
To be more precise `Sequence[tuple[str, str]]`.

2024-04-15 06:21 UTC, pchorus commented on invalid_package_versions/runner.py
> +    return tuple(invalid_versions)
I like it as a comprehension and refactored it accordingly. Not sure about the 🦭 operator though.

2024-04-15 06:21 UTC, pchorus commented on invalid_package_versions/runner.py
> +            invalid_versions.append((package, version_str))
Did this when refactored it to list comprehension.

2024-04-15 06:56 UTC, pchorus commented on suspicious-package-versions.py
> +        *poetry_data["dev-dependencies"].items()
Fixed the path stuff by using directory of test file and added test data file path relative to the current file.

2024-04-15 06:56 UTC, mm-matthias commented on invalid_package_versions/runner.py
> +IGNORE_PACKAGES = ["boto3"]
```suggestion
IGNORE_PACKAGES = ("boto3",)
```

2024-04-15 06:56 UTC, mm-matthias commented on invalid_package_versions/runner.py
> +def check_invalid_package_versions(pyproject_data) -> Sequence[tuple[str, str]]:
```suggestion
def check_invalid_package_versions(pyproject_data: dict) -> Sequence[tuple[str, str]]:
```

2024-04-15 06:57 UTC, pchorus commented
I added a `IGNORE_PACKAGES` containing a tuple of package names that should be ignored. Currently, it only contains "boto3".

2024-04-15 06:58 UTC, pchorus commented on invalid_package_versions/runner.py
> +    return tuple(invalid_versions)
Fighted the walrus with @catcombo.
🐈‍⬛ 🦭🐈‍⬛

2024-04-15 06:59 UTC, mm-matthias commented on invalid_package_versions/runner.py
> +    if invalid_versions:
```suggestion
    if (invalid_versions := get_invalid_package_versions(data)):
```

2024-04-15 06:59 UTC, mm-matthias commented on invalid_package_versions/runner.py
> +def check_invalid_package_versions(pyproject_data) -> Sequence[tuple[str, str]]:
I would name this `get_invalid_package_versions`, because it just returns some data. If it is named `check_` my expectation is that it raises some exception upon some case.

2024-04-15 06:59 UTC, catcombo approved these changes
:+1:

2024-04-15 07:26 UTC, catcombo commented on invalid_package_versions/tests/test_get_invalid_package_versions.py
> +class GetInvalidPackageVersions(TestCase):
```suggestion
class GetInvalidPackageVersionsTest(TestCase):
```

2024-04-15 08:10 UTC, marns93 approved these changes
Thanks for adding the tests.
LGTM. :)

2024-04-15 08:10 UTC, marns93 commented on .github/workflows/ci.yml
> +      - run: poetry run python -m pytest --cov --cov-fail-under=45
Newline missing

2024-04-15 09:54 UTC, merged