fix(action): use correct path to check invalid package versions
moneymeets/action-setup-python-poetry pull request #23
Opened 2024-04-15 10:20 UTC by marns93

As you can see in https://github.com/moneymeets/moneymeets-tenants/actions/runs/8687316068, the script cannot be found.
We introduced unittests and created a python package and missed to update the path in `action.yml`.

This should fix the problem.

2024-04-15 10:21 UTC, felix11h approved these changes
Thank you for the quick fix! 👍

2024-04-15 10:51 UTC, pchorus requested changes
No, this is not the correct fix in my opinion. I am working on a fix and we should run the code not as a script, but as a module using something like: `poetry run --directory ${{ github.action_path }} merge_checks_runner`.

So let's fix it in this PR or close it and I take care. However you like it.

2024-04-15 11:21 UTC, marns93 commented
> > No, this is not the correct fix in my opinion. I am working on a fix and we should run the code not as a script, but as a module using something like: `poetry run --directory ${{ github.action_path }} merge_checks_runner`.
> > So let's fix it in this PR or close it and I take care. However you like it.
> 
> I'm fine with defining a poetry run command, then you need to add it to `pyproject.toml` as we did for merge-checks, see: https://github.com/moneymeets/action-merge-checks/blob/master/pyproject.toml#L8
> 
> So anyway if the package name will be updated, you have to update the `pyproject.toml` as well. Will update this in here.

Okay, I see it is in there, but with the wrong name, see: https://github.com/moneymeets/action-setup-python-poetry/blob/master/pyproject.toml#L9

2024-04-15 11:42 UTC, marns93 commented
> 🤦🏻‍♂️ Alright, I forgot to change the name. Thank you!

Seems to not work without further investigation: https://github.com/moneymeets/moneymeets-pulumi/actions/runs/8687488458/job/23823463275

Using the full script path without defining it would work: https://github.com/moneymeets/moneymeets-pulumi/actions/runs/8687488458/job/23821080618

I would prefer to disable the check, fix it and test it in our most used repositories first.
What do you think @pchorus ?

2024-04-19 04:06 UTC, closed without merging

2024-04-19 04:17 UTC, pchorus commented
Check was removed and I will prepare a proper new PR. Thus, this PR is closed.