Feature/check package versions
moneymeets/action-setup-python-poetry pull request #24
Opened 2024-04-19 11:14 UTC by pchorus

Second try. Now I made sure that the action works correctly in GitHub Actions.

Fixes for repositories to fullfil requirements for poetry package versions follow shortly.

2024-04-19 11:25 UTC, pchorus commented
Created ticket MD-7262 to track these changes.

2024-04-19 13:44 UTC, catcombo approved these changes

2024-04-19 15:42 UTC, mm-matthias approved these changes

2024-04-22 05:43 UTC, marns93 requested changes
Please remove the files which are managed by Pulumi.

2024-04-22 05:43 UTC, marns93 commented on ruff.toml
> +# https://docs.astral.sh/ruff/configuration/
This file is managed by Pulumi and will be deployed with your changes in https://github.com/moneymeets/moneymeets-pulumi/pull/572

2024-04-22 05:43 UTC, marns93 commented on .idea/watcherTasks.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file is managed by Pulumi and will be deployed with your changes in https://github.com/moneymeets/moneymeets-pulumi/pull/572

2024-04-22 06:28 UTC, marns93 approved these changes

2024-04-22 06:41 UTC, pchorus commented
/rebase

2024-04-23 10:21 UTC, pchorus commented
There are even more repositories that needed updates to their `pyproject.toml`. I hope I changed them all accordingly.

2024-04-23 10:21 UTC, merged