Feature/bump versions
moneymeets/action-setup-python-poetry pull request #7
Opened 2022-09-06 06:57 UTC by marns93

In this PR I've updated the default Poetry version to 1.2.0. @felix11h tested the Version and it is already updated in our Heroku buildpack. You can use the new version with old lockfile.
Furthermore the default Python version is updated to 3.10.6. All repositories except APIs are using this. The pipelines of APIs repositories are pinned to Python 3.10.5 and needs to be updated by hand.

@zyv @mm-matthias FYI

2022-09-06 07:42 UTC, zyv approved these changes
Ah, I finally understand why @marns93 meant that we need to coordinate this with Python upgrades - because you can also bump the default Python version here...

2022-09-06 08:29 UTC, felix11h requested changes

2022-09-06 08:29 UTC, felix11h commented on action.yml
>          path: ~/.cache/pypoetry/virtualenvs
Looks great to me, @marns93. Just this one thought: Do you think it would be a good idea to set the virtualenvs path in Poetry explicity? We could add something like
```sh
poetry config virtualenvs.path /home/runner/.cache/pypoetry/virtualenvs
```
to the "Install and configure Poetry" step. The default virtualenv path might change in the future, and we would likely only notice that our caching is broken by workflow runs suddenly taking longer.

2022-09-07 08:21 UTC, felix11h approved these changes

2022-09-07 08:21 UTC, marns93 commented on action.yml
>          path: ~/.cache/pypoetry/virtualenvs
Good idea @felix11h .
I've updated it in https://github.com/moneymeets/action-setup-python-poetry/pull/7/commits/4ca0e20d560f87ee06d7b47d13dacb3b5cecb894

My test pipeline: https://github.com/moneymeets/moneymeets-tenants/runs/8223211285?check_suite_focus=true
You will find two attempts. The first one without cache, the second with existing cache.

2022-09-07 08:24 UTC, merged